# Generated by Django 3.1 on 2020-12-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(help_text='닉네임을 입력하세요', max_length=200)),
                ('gender', models.CharField(max_length=10)),
                ('birth', models.DateField(verbose_name='User_birth')),
                ('life', models.IntegerField(default=100)),
            ],
        ),
    ]
