# Generated by Django 3.1.4 on 2020-12-28 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odoyApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='odoyUser',
            new_name='User_Info',
        ),
    ]
